name: Build and push latest images

on:
  push:
    tags:
      - "v[0-9]+\.[0-9]+\.[0-9]+"
  workflow_dispatch:
    inputs:
      custom_tag:
        description: 'New version to tag and push image (in SemVer)'
        required: true
        default: 'v0.0.0'


env:
  IMG_REGISTRY_HOST: quay.io
  IMG_REGISTRY_ORG: kuadrant
  IMG_NAME: testsuite

jobs:
  build-latest:
    name: Build and push image
    runs-on: ubuntu-latest
    env:
      # Choose tag input based on this workflow trigger type
      IMG_TAGS: ${{ github.event_name == 'workflow_dispatch' && inputs.custom_tag || github.ref_name }} latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Create Git tag
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          git tag ${{ inputs.custom_tag }}
          git push origin ${{ inputs.custom_tag }}
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMG_NAME }}
          tags: ${{ env.IMG_TAGS }}
          layers: true
          platforms: linux/amd64
          containerfiles: |
            ./Dockerfile
      - name: Push Image
        if: ${{ !env.ACT }}
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMG_REGISTRY_HOST }}/${{ env.IMG_REGISTRY_ORG }}
          username: ${{ secrets.IMG_REGISTRY_USERNAME }}
          password: ${{ secrets.IMG_REGISTRY_TOKEN }}
      - name: 'Build Changelog'
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
        token: '${{ github.token }}'
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
